use super::*;

pub fn run(config: WindowsHostConfig) -> Result<()> {
    let app = HostDashboard::new()?;
    app.set_product(SharedString::from(config.product.clone()));
    app.set_version(SharedString::from(config.version.clone()));
    app.set_mode(SharedString::from(if config.remote_enabled {
        "Remote relay enabled"
    } else {
        "Local only"
    }));
    app.set_status_summary(SharedString::from(if config.remote_enabled {
        format!(
            "Remote relay enabled | local API {} | gateway {}",
            config.health_url, config.gateway_base_url
        )
    } else {
        format!("Local only | local API {}", config.health_url)
    }));
    app.set_identity_id(SharedString::from(config.identity_id.clone()));
    app.set_device_id(SharedString::from(config.device_id.clone()));
    app.set_management_stats(SharedString::from(format!(
        "Live redacted statistics are available at http://127.0.0.1:{}/ui and /ui/status.\n\nYian Host may show authorization modes, required grid cells, managed-object call counts, agent/requester counts, remote-interface access counts, and error-call totals.\n\nStory template candidates can be generated by Host and queued at /story-template/generate; StoryLock must explicitly pull them from /story-template/candidates. Host never invokes StoryLock.\n\nLLM keys are direct-access generator config. Host may show configured/missing, but must not display key values.\n\nIt must not display StoryLock drafts, vault files, package paths, question answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.",
        config.host_port
    )));
    app.set_diagnostics(SharedString::from(
        "Yian Host is storage-blind. It does not read or display StoryLock drafts, vault files, manifests, catalogs, templates, package paths, question answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.\n\nThe local API exists for loopback health checks and diagnostics only. Remote capability names and call chains are surfaced in observation mode, not as user workflow steps.",
    ));
    let saved_settings = Rc::new(RefCell::new(load_storylock_ui_settings()));
    let initial_language = saved_settings
        .borrow()
        .language
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| String::from("zh"));
    app.set_language(SharedString::from(initial_language.clone()));

    let local_health_url = config.health_url.clone();
    app.on_test_local_host(move || {
        SharedString::from(test_http_endpoint("Local Host", &local_health_url))
    });

    let remote_gateway_url = config.gateway_base_url.clone();
    app.on_test_remote_connection(move || {
        SharedString::from(test_http_endpoint("Remote Gateway", &remote_gateway_url))
    });

    let host_port_for_nine_grid = config.host_port;
    app.on_test_managed_object_nine_grid(move |tier| {
        SharedString::from(test_managed_object_nine_grid(
            host_port_for_nine_grid,
            tier.to_string(),
        ))
    });

    let host_language = Rc::new(RefCell::new(initial_language));
    let normalized_settings = {
        let mut settings = saved_settings.borrow().clone();
        normalize_storylock_ui_settings(&mut settings);
        settings
    };
    *saved_settings.borrow_mut() = normalized_settings.clone();
    if let Err(error) = save_storylock_ui_settings(&normalized_settings) {
        eprintln!("failed to normalize StoryLock UI settings: {error}");
    }
    let core_package_dir = resolve_storylock_core_package_with_conflict_prompt(
        &initial_storylock_core_package_dir(&normalized_settings),
        normalized_settings
            .export_package_dir
            .as_deref()
            .map(Path::new),
        Some(&config.data_dir),
    )?;
    let _ = ensure_storylock_core_package(&core_package_dir);
    app.set_storylock_data_dir(SharedString::from(core_package_dir.display().to_string()));
    app.set_package_self_check(SharedString::from(package_dir_status_report(&core_package_dir)));
    app.set_status_summary(SharedString::from(if config.remote_enabled {
        format!(
            "Remote relay enabled | local API {} | gateway {} | package {}",
            config.health_url,
            config.gateway_base_url,
            core_package_dir.display()
        )
    } else {
        format!(
            "Local only | local API {} | package {}",
            config.health_url,
            core_package_dir.display()
        )
    }));
    app.set_management_stats(SharedString::from(format!(
        "Live redacted statistics are available at http://127.0.0.1:{}/ui and /ui/status.\n\n{}\n\nYian Host reads learning-policy.json for retention-learning scheduling, but does not read StoryLock drafts, vault files, question text, answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.",
        config.host_port,
        host_learning_plan_status(&core_package_dir)
    )));

    let core_window: Rc<RefCell<Option<StoryLockCoreApp>>> = Rc::new(RefCell::new(None));
    let settings_window: Rc<RefCell<Option<SettingsDialog>>> = Rc::new(RefCell::new(None));
    let storylock_auth_window: Rc<RefCell<Option<StoryLockAuthorizationDialog>>> =
        Rc::new(RefCell::new(None));
    let settings_window_for_open = Rc::clone(&settings_window);
    let host_for_settings = app.as_weak();
    let host_language_for_settings = Rc::clone(&host_language);
    let core_window_for_settings = Rc::clone(&core_window);
    let host_for_settings_lock = app.as_weak();
    let shared_status = Rc::new(RefCell::new(String::from("")));
    let shared_status_for_settings = Rc::clone(&shared_status);
    let saved_settings_for_settings = Rc::clone(&saved_settings);
    let host_for_main_browse = app.as_weak();
    let host_language_for_main_browse = Rc::clone(&host_language);
    let saved_settings_for_main_browse = Rc::clone(&saved_settings);
    let core_window_for_main_browse = Rc::clone(&core_window);

    app.on_browse_storylock_data_dir(move || {
        let current_dir = initial_storylock_core_package_dir(&saved_settings_for_main_browse.borrow());
        let Some(selected_path) = pick_storylock_core_package_path(current_dir.as_path()) else {
            return;
        };
        let package_dir = resolve_storylock_core_package_path(&selected_path);
        match ensure_storylock_core_package(&package_dir) {
            Ok(()) => {
                let language = host_language_for_main_browse.borrow().clone();
                let next_settings = merge_host_settings(
                    &saved_settings_for_main_browse.borrow(),
                    &language,
                    Some(package_dir.display().to_string()),
                );
                if let Err(error) = save_storylock_ui_settings(&next_settings) {
                    if let Some(host) = host_for_main_browse.upgrade() {
                        host.set_connection_test_status(SharedString::from(format!(
                            "StoryLock encrypted files path save failed: {error}"
                        )));
                    }
                    return;
                }
                *saved_settings_for_main_browse.borrow_mut() = next_settings;
                if let Some(core) = core_window_for_main_browse.borrow().as_ref() {
                    initialize_storylock_core_empty_window(core, &package_dir);
                    core.set_language(SharedString::from(language));
                }
                if let Some(host) = host_for_main_browse.upgrade() {
                    host.set_storylock_data_dir(SharedString::from(
                        package_dir.display().to_string(),
                    ));
                    host.set_package_self_check(SharedString::from(
                        package_dir_status_report(&package_dir),
                    ));
                    host.set_connection_test_status(SharedString::from(
                        "StoryLock package directory selected.",
                    ));
                }
            }
            Err(error) => {
                if let Some(host) = host_for_main_browse.upgrade() {
                    host.set_connection_test_status(SharedString::from(format!(
                        "StoryLock package load failed: {error}"
                    )));
                }
            }
        }
    });

    app.on_open_settings(move || {
        let existing_show_result = {
            settings_window_for_open
                .borrow()
                .as_ref()
                .map(|existing| existing.show())
        };
        if let Some(show_result) = existing_show_result {
            if let Err(error) = show_result {
                eprintln!("failed to show settings window: {error}");
                *settings_window_for_open.borrow_mut() = None;
                if let Some(host) = host_for_settings.upgrade() {
                    host.set_settings_open(false);
                    host.set_connection_test_status(SharedString::from(format!(
                        "Settings reopen failed: {error}"
                    )));
                }
            } else if let Some(host) = host_for_settings.upgrade() {
                host.set_settings_open(true);
                host.set_connection_test_status(SharedString::from("Settings opened"));
            }
            return;
        }

        match SettingsDialog::new() {
            Ok(settings) => {
                settings.set_language(SharedString::from(
                    host_language_for_settings.borrow().clone(),
                ));
                settings.set_core_launch_status(SharedString::from(
                    shared_status_for_settings.borrow().clone(),
                ));
                settings.set_encrypted_data_dir(SharedString::from(
                    initial_storylock_core_package_dir(&saved_settings_for_settings.borrow())
                        .display()
                        .to_string(),
                ));

                if let Some(host) = host_for_settings.upgrade() {
                    host.set_connection_test_status(SharedString::from("Settings opened"));
                    host.set_settings_open(true);
                }

                let settings_weak = settings.as_weak();
                let settings_weak_for_close = settings_weak.clone();
                let host_for_language = host_for_settings.clone();
                let host_language_for_language = Rc::clone(&host_language_for_settings);
                let core_window_for_language = Rc::clone(&core_window_for_settings);
                let saved_settings_for_language = Rc::clone(&saved_settings_for_settings);

                settings.on_language_changed(move |language| {
                    let language_string = language.to_string();
                    *host_language_for_language.borrow_mut() = language_string.clone();
                    let next_settings = merge_host_settings(
                        &saved_settings_for_language.borrow(),
                        &language_string,
                        None,
                    );
                    if let Err(error) = save_storylock_ui_settings(&next_settings) {
                        eprintln!("failed to save StoryLock UI settings: {error}");
                    }
                    *saved_settings_for_language.borrow_mut() = next_settings;

                    if let Some(settings) = settings_weak.upgrade() {
                        settings.set_language(SharedString::from(language_string.clone()));
                    }
                    if let Some(host) = host_for_language.upgrade() {
                        host.set_language(SharedString::from(language_string.clone()));
                        host.set_connection_test_status(SharedString::from(
                            "Language changed, settings stay open",
                        ));
                    }
                    if let Some(core) = core_window_for_language.borrow().as_ref() {
                        core.set_language(SharedString::from(language_string));
                    }
                });

                let settings_weak_for_browse = settings.as_weak();
                let host_for_browse = host_for_settings.clone();
                let host_language_for_browse = Rc::clone(&host_language_for_settings);
                let core_window_for_browse = Rc::clone(&core_window_for_settings);
                let saved_settings_for_browse = Rc::clone(&saved_settings_for_settings);
                settings.on_browse_encrypted_data_dir(move || {
                    let Some(settings) = settings_weak_for_browse.upgrade() else {
                        return;
                    };
                    let current_dir =
                        initial_storylock_core_package_dir(&saved_settings_for_browse.borrow());
                    let selected_path = pick_storylock_core_package_path(current_dir.as_path());
                    let Some(selected_path) = selected_path else {
                        return;
                    };
                    let package_dir = resolve_storylock_core_package_path(&selected_path);
                    match ensure_storylock_core_package(&package_dir) {
                        Ok(()) => {
                            settings.set_encrypted_data_dir(SharedString::from(
                                package_dir.display().to_string(),
                            ));
                            let language = host_language_for_browse.borrow().clone();
                            let next_settings = merge_host_settings(
                                &saved_settings_for_browse.borrow(),
                                &language,
                                Some(package_dir.display().to_string()),
                            );
                            if let Err(error) = save_storylock_ui_settings(&next_settings) {
                                if let Some(host) = host_for_browse.upgrade() {
                                    host.set_connection_test_status(SharedString::from(format!(
                                        "Encrypted files path save failed: {error}"
                                    )));
                                }
                                return;
                            }
                            *saved_settings_for_browse.borrow_mut() = next_settings;
                            if let Some(core) = core_window_for_browse.borrow().as_ref() {
                                initialize_storylock_core_empty_window(core, &package_dir);
                                core.set_language(SharedString::from(language));
                            }
                            if let Some(host) = host_for_browse.upgrade() {
                                host.set_connection_test_status(SharedString::from(
                                    "Package directory selected.",
                                ));
                            }
                        }
                        Err(error) => {
                            if let Some(host) = host_for_browse.upgrade() {
                                host.set_connection_test_status(SharedString::from(format!(
                                    "Package load failed: {error}"
                                )));
                            }
                        }
                    }
                });

                let host_for_settings_lock_close = host_for_settings_lock.clone();
                let host_language_for_close = Rc::clone(&host_language_for_settings);
                let saved_settings_for_close = Rc::clone(&saved_settings_for_settings);
                let settings_window_for_close = Rc::clone(&settings_window_for_open);
                let close_settings = Rc::new(move |settings: &SettingsDialog| {
                    let next_settings = merge_host_settings(
                        &saved_settings_for_close.borrow(),
                        &host_language_for_close.borrow(),
                        Some(settings.get_encrypted_data_dir().to_string()),
                    );
                    if let Err(error) = save_storylock_ui_settings(&next_settings) {
                        eprintln!("failed to save StoryLock UI settings: {error}");
                    } else {
                        *saved_settings_for_close.borrow_mut() = next_settings;
                    }
                    let _ = settings.hide();
                    *settings_window_for_close.borrow_mut() = None;
                    if let Some(host) = host_for_settings_lock_close.upgrade() {
                        host.set_settings_open(false);
                        let text = if host_language_for_close.borrow().as_str() == "zh" {
                            "设置已关闭"
                        } else {
                            "Settings closed"
                        };
                        host.set_connection_test_status(SharedString::from(text));
                    }
                });

                let close_settings_for_button = Rc::clone(&close_settings);
                settings.on_close_requested(move || {
                    if let Some(settings) = settings_weak_for_close.upgrade() {
                        close_settings_for_button(&settings);
                    }
                });

                let settings_weak_for_window_close = settings.as_weak();
                let close_settings_for_window = Rc::clone(&close_settings);
                settings.window().on_close_requested(move || {
                    if let Some(settings) = settings_weak_for_window_close.upgrade() {
                        close_settings_for_window(&settings);
                    }
                    slint::CloseRequestResponse::HideWindow
                });

                if let Err(error) = settings.show() {
                    eprintln!("failed to show settings window: {error}");
                    return;
                }
                *settings_window_for_open.borrow_mut() = Some(settings);
            }
            Err(error) => eprintln!("failed to create settings window: {error}"),
        }
    });

    let core_window_for_callback = Rc::clone(&core_window);
    let host_for_storylock_close = app.as_weak();
    let settings_window_for_storylock_close = Rc::clone(&settings_window);
    let shared_status_for_storylock_close = Rc::clone(&shared_status);
    let host_language_for_storylock = Rc::clone(&host_language);
    let saved_settings_for_storylock = Rc::clone(&saved_settings);
    let storylock_auth_window_for_open = Rc::clone(&storylock_auth_window);
    let host_port_for_storylock_auth = config.host_port;

    app.on_open_storylock_core(move || {
        let Some(host) = host_for_storylock_close.upgrade() else {
            return;
        };
        host.set_connection_test_status(SharedString::from(
            "StoryLock opened in empty mode. Select or confirm the current package, then unlock it to load current package content.",
        ));
        open_storylock_core_in_empty_mode(
            host_for_storylock_close.clone(),
            Rc::clone(&core_window_for_callback),
            Rc::clone(&settings_window_for_storylock_close),
            Rc::clone(&shared_status_for_storylock_close),
            Rc::clone(&host_language_for_storylock),
            Rc::clone(&saved_settings_for_storylock),
            Rc::clone(&storylock_auth_window_for_open),
            host_port_for_storylock_auth,
        );
    });

    let weak = app.as_weak();
    let host_language_for_close = Rc::clone(&host_language);
    let saved_settings_for_close = Rc::clone(&saved_settings);
    app.on_close_requested(move || {
        let next_settings = merge_host_settings(
            &saved_settings_for_close.borrow(),
            &host_language_for_close.borrow(),
            None,
        );
        if let Err(error) = save_storylock_ui_settings(&next_settings) {
            eprintln!("failed to save StoryLock UI settings: {error}");
        }
        *saved_settings_for_close.borrow_mut() = next_settings;
        if let Some(app) = weak.upgrade() {
            let _ = app.hide();
        }
    });

    app.run()?;
    let final_settings =
        merge_host_settings(&saved_settings.borrow(), &host_language.borrow(), None);
    if let Err(error) = save_storylock_ui_settings(&final_settings) {
        eprintln!("failed to save StoryLock UI settings: {error}");
    }
    Ok(())
}

fn open_storylock_core_in_empty_mode(
    host_weak: slint::Weak<HostDashboard>,
    core_window: Rc<RefCell<Option<StoryLockCoreApp>>>,
    settings_window: Rc<RefCell<Option<SettingsDialog>>>,
    shared_status: Rc<RefCell<String>>,
    host_language: Rc<RefCell<String>>,
    saved_settings: Rc<RefCell<StoryLockUiSettings>>,
    auth_window: Rc<RefCell<Option<StoryLockAuthorizationDialog>>>,
    host_port: u16,
) {
    if let Some(host) = host_weak.upgrade() {
        host.set_connection_test_status(SharedString::from(
            "StoryLock Core opened in empty mode. Current package content stays unloaded until unlock.",
        ));
    }
    let current_settings = saved_settings.borrow().clone();
    let active_package_dir = initial_storylock_core_package_dir(&current_settings);
    if let Err(error) = ensure_storylock_core_package(&active_package_dir) {
        eprintln!("failed to initialize StoryLock Core package: {error}");
    }

    if let Some(core) = core_window.borrow().as_ref() {
        initialize_storylock_core_empty_window(core, &active_package_dir);
        core.set_language(SharedString::from(host_language.borrow().clone()));
        apply_storylock_ui_settings(core, &current_settings);
        if let Err(error) = core.show() {
            eprintln!("failed to show existing StoryLock Core window: {error}");
        }
        return;
    }

    *core_window.borrow_mut() = None;
    match StoryLockCoreApp::new() {
        Ok(core) => {
            core.set_language(SharedString::from(host_language.borrow().clone()));
            initialize_storylock_core_empty_window(&core, &active_package_dir);
            apply_storylock_ui_settings(&core, &current_settings);
            let host_for_closed = host_weak.clone();
            let settings_window_for_closed = Rc::clone(&settings_window);
            let shared_status_for_closed = Rc::clone(&shared_status);
            let notify_storylock_closed: Rc<dyn Fn()> = Rc::new(move || {
                let status = "StoryLock closed".to_string();
                *shared_status_for_closed.borrow_mut() = status.clone();
                if let Some(host) = host_for_closed.upgrade() {
                    host.set_connection_test_status(SharedString::from(status.clone()));
                }
                if let Some(settings) = settings_window_for_closed.borrow().as_ref() {
                    settings.set_core_launch_status(SharedString::from(status));
                }
            });
            let host_for_unlock = host_weak.clone();
            let core_window_for_unlock = Rc::clone(&core_window);
            let settings_window_for_unlock = Rc::clone(&settings_window);
            let shared_status_for_unlock = Rc::clone(&shared_status);
            let host_language_for_unlock = Rc::clone(&host_language);
            let saved_settings_for_unlock = Rc::clone(&saved_settings);
            let auth_window_for_unlock = Rc::clone(&auth_window);
            let unlock_package: Rc<dyn Fn()> = Rc::new(move || {
                if let Some(host) = host_for_unlock.upgrade() {
                    host.set_connection_test_status(SharedString::from(
                        "StoryLock unlock requested. Complete the current package challenge to load current package content.",
                    ));
                }
                if let Err(error) = begin_storylock_open_authorization(
                    host_port,
                    host_for_unlock.clone(),
                    Rc::clone(&core_window_for_unlock),
                    Rc::clone(&settings_window_for_unlock),
                    Rc::clone(&shared_status_for_unlock),
                    Rc::clone(&host_language_for_unlock),
                    Rc::clone(&saved_settings_for_unlock),
                    Rc::clone(&auth_window_for_unlock),
                ) {
                    if let Some(host) = host_for_unlock.upgrade() {
                        host.set_connection_test_status(SharedString::from(format!(
                            "StoryLock unlock blocked: {error}"
                        )));
                    }
                }
            });
            wire_storylock_core_callbacks(
                &core,
                active_package_dir,
                Rc::clone(&core_window),
                notify_storylock_closed,
                unlock_package,
                host_port,
            );
            if let Err(error) = core.show() {
                eprintln!("failed to show StoryLock Core window: {error}");
                return;
            }
            *core_window.borrow_mut() = Some(core);
        }
        Err(error) => {
            eprintln!("failed to create StoryLock Core window: {error}");
        }
    }
}

fn open_storylock_core_after_authorization(
    host_weak: slint::Weak<HostDashboard>,
    core_window: Rc<RefCell<Option<StoryLockCoreApp>>>,
    settings_window: Rc<RefCell<Option<SettingsDialog>>>,
    shared_status: Rc<RefCell<String>>,
    host_language: Rc<RefCell<String>>,
    saved_settings: Rc<RefCell<StoryLockUiSettings>>,
    host_port: u16,
) {
    if let Some(host) = host_weak.upgrade() {
        host.set_connection_test_status(SharedString::from(
            "StoryLock authorization passed. Current package content is now loading.",
        ));
    }
    let current_settings = saved_settings.borrow().clone();
    let active_package_dir = initial_storylock_core_package_dir(&current_settings);
    if let Err(error) = ensure_storylock_core_package(&active_package_dir) {
        eprintln!("failed to initialize StoryLock Core package: {error}");
    }

    if let Some(core) = core_window.borrow().as_ref() {
        initialize_storylock_core_window(core, &active_package_dir);
        core.set_language(SharedString::from(host_language.borrow().clone()));
        apply_storylock_ui_settings(core, &current_settings);
        set_storylock_start_page_to_questions(core);
        core.set_config_status(SharedString::from(
            "StoryLock Core is already open. Existing local window was focused.",
        ));
        if let Err(error) = core.show() {
            eprintln!("failed to show existing StoryLock Core window: {error}");
        }
        return;
    }

    *core_window.borrow_mut() = None;
    match StoryLockCoreApp::new() {
        Ok(core) => {
            core.set_language(SharedString::from(host_language.borrow().clone()));
            initialize_storylock_core_window(&core, &active_package_dir);
            apply_storylock_ui_settings(&core, &current_settings);
            set_storylock_start_page_to_questions(&core);
            let host_for_closed = host_weak.clone();
            let settings_window_for_closed = Rc::clone(&settings_window);
            let shared_status_for_closed = Rc::clone(&shared_status);
            let notify_storylock_closed: Rc<dyn Fn()> = Rc::new(move || {
                let status = "StoryLock closed".to_string();
                *shared_status_for_closed.borrow_mut() = status.clone();
                if let Some(host) = host_for_closed.upgrade() {
                    host.set_connection_test_status(SharedString::from(status.clone()));
                }
                if let Some(settings) = settings_window_for_closed.borrow().as_ref() {
                    settings.set_core_launch_status(SharedString::from(status));
                }
            });
            let unlock_package: Rc<dyn Fn()> = Rc::new(|| {});
            wire_storylock_core_callbacks(
                &core,
                active_package_dir,
                Rc::clone(&core_window),
                notify_storylock_closed,
                unlock_package,
                host_port,
            );
            if let Err(error) = core.show() {
                eprintln!("failed to show StoryLock Core window: {error}");
                return;
            }
            *core_window.borrow_mut() = Some(core);
        }
        Err(error) => {
            eprintln!("failed to create StoryLock Core window: {error}");
        }
    }
}

fn test_http_endpoint(label: &str, url: &str) -> String {
    let client = match Client::builder().timeout(Duration::from_secs(5)).build() {
        Ok(client) => client,
        Err(error) => return format!("{label}: client setup failed: {error}"),
    };
    match client.get(url).send() {
        Ok(response) if response.status().is_success() => {
            format!("{label}: OK ({})", response.status())
        }
        Ok(response) => format!("{label}: HTTP {}", response.status()),
        Err(error) => format!("{label}: failed: {error}"),
    }
}

fn begin_storylock_open_authorization(
    host_port: u16,
    host_weak: slint::Weak<HostDashboard>,
    core_window: Rc<RefCell<Option<StoryLockCoreApp>>>,
    settings_window: Rc<RefCell<Option<SettingsDialog>>>,
    shared_status: Rc<RefCell<String>>,
    host_language: Rc<RefCell<String>>,
    saved_settings: Rc<RefCell<StoryLockUiSettings>>,
    auth_window: Rc<RefCell<Option<StoryLockAuthorizationDialog>>>,
) -> Result<()> {
    let existing_show_result = auth_window
        .borrow()
        .as_ref()
        .map(|existing| existing.show());
    if let Some(show_result) = existing_show_result {
        if let Err(error) = show_result {
            *auth_window.borrow_mut() = None;
            return Err(anyhow::anyhow!("authorization window reopen failed: {error}"));
        }
        return Ok(());
    }

    let language = host_language.borrow().clone();
    let active_package_dir = initial_storylock_core_package_dir(&saved_settings.borrow());
    ensure_storylock_core_package(&active_package_dir)?;
    let cells = create_storylock_open_challenge(&active_package_dir, 22)?;

    let dialog = StoryLockAuthorizationDialog::new()?;
    dialog.set_is_zh(language == "zh");
    dialog.set_challenge_count(cells.len() as i32);
    let selections = Rc::new(RefCell::new(vec![Vec::<String>::new(); cells.len()]));
    let current_index = Rc::new(Cell::new(0usize));
    set_storylock_challenge_question(&dialog, &cells, &selections.borrow(), current_index.get());

    let dialog_weak = dialog.as_weak();
    let host_for_auth = host_weak.clone();
    let cells_for_auth = cells.clone();
    let core_window_for_auth = Rc::clone(&core_window);
    let settings_window_for_auth = Rc::clone(&settings_window);
    let shared_status_for_auth = Rc::clone(&shared_status);
    let host_language_for_auth = Rc::clone(&host_language);
    let saved_settings_for_auth = Rc::clone(&saved_settings);
    let auth_window_for_auth = Rc::clone(&auth_window);
    let selections_for_auth = Rc::clone(&selections);
    let current_index_for_auth = Rc::clone(&current_index);
    dialog.on_authorize_requested(move || {
        let Some(dialog) = dialog_weak.upgrade() else {
            return;
        };
        let answers = selections_for_auth.borrow().clone();
        if answers.iter().any(Vec::is_empty) {
            show_storylock_authorization_result(
                "StoryLock 九宫格挑战",
                "挑战未完成：请完成全部 22 题后再授权。",
                false,
            );
            if let Some(host) = host_for_auth.upgrade() {
                host.set_connection_test_status(SharedString::from(
                    "StoryLock open blocked: complete every grid challenge selection first.",
                ));
            }
            return;
        }
        match authorize_storylock_open(&cells_for_auth, &answers) {
            Ok(()) => {
                show_storylock_authorization_result(
                    "StoryLock 九宫格挑战",
                    "挑战通过，即将进入 StoryLock 编辑界面。",
                    true,
                );
                let _ = dialog.hide();
                *auth_window_for_auth.borrow_mut() = None;
                open_storylock_core_after_authorization(
                    host_for_auth.clone(),
                    Rc::clone(&core_window_for_auth),
                    Rc::clone(&settings_window_for_auth),
                    Rc::clone(&shared_status_for_auth),
                    Rc::clone(&host_language_for_auth),
                    Rc::clone(&saved_settings_for_auth),
                    host_port,
                );
            }
            Err(error) => {
                let message = format!("StoryLock authorization failed: {error}");
                show_storylock_authorization_result(
                    "StoryLock 九宫格挑战",
                    &format!("挑战失败：{error}"),
                    false,
                );
                {
                    let mut selections = selections_for_auth.borrow_mut();
                    for selection in selections.iter_mut() {
                        selection.clear();
                    }
                }
                current_index_for_auth.set(0);
                set_storylock_challenge_question(
                    &dialog,
                    &cells_for_auth,
                    &selections_for_auth.borrow(),
                    0,
                );
                if let Some(host) = host_for_auth.upgrade() {
                    host.set_connection_test_status(SharedString::from(message));
                }
            }
        }
    });

    let dialog_weak = dialog.as_weak();
    let cells_for_select = cells.clone();
    let selections_for_select = Rc::clone(&selections);
    let current_index_for_select = Rc::clone(&current_index);
    dialog.on_select_answer(move |answer_index| {
        let index = current_index_for_select.get();
        let selected = cells_for_select
            .get(index)
            .and_then(|cell| cell.answer_options.get(answer_index as usize))
            .cloned()
            .unwrap_or_default();
        if !selected.trim().is_empty() {
            toggle_storylock_challenge_selection(
                &cells_for_select,
                &mut selections_for_select.borrow_mut(),
                index,
                answer_index as usize,
            );
        }
        if let Some(dialog) = dialog_weak.upgrade() {
            set_storylock_challenge_question(
                &dialog,
                &cells_for_select,
                &selections_for_select.borrow(),
                index,
            );
        }
    });

    let dialog_weak = dialog.as_weak();
    let cells_for_previous = cells.clone();
    let selections_for_previous = Rc::clone(&selections);
    let current_index_for_previous = Rc::clone(&current_index);
    dialog.on_previous_requested(move || {
        if current_index_for_previous.get() == 0 {
            return;
        }
        let next_index = current_index_for_previous.get().saturating_sub(1);
        current_index_for_previous.set(next_index);
        if let Some(dialog) = dialog_weak.upgrade() {
            set_storylock_challenge_question(
                &dialog,
                &cells_for_previous,
                &selections_for_previous.borrow(),
                next_index,
            );
        }
    });

    let dialog_weak = dialog.as_weak();
    let cells_for_next = cells.clone();
    let selections_for_next = Rc::clone(&selections);
    let current_index_for_next = Rc::clone(&current_index);
    dialog.on_next_requested(move || {
        let max_index = cells_for_next.len().saturating_sub(1);
        if current_index_for_next.get() >= max_index {
            return;
        }
        let next_index = (current_index_for_next.get() + 1).min(max_index);
        current_index_for_next.set(next_index);
        if let Some(dialog) = dialog_weak.upgrade() {
            set_storylock_challenge_question(
                &dialog,
                &cells_for_next,
                &selections_for_next.borrow(),
                next_index,
            );
        }
    });

    let dialog_weak = dialog.as_weak();
    let host_for_cancel = host_weak.clone();
    let auth_window_for_cancel = Rc::clone(&auth_window);
    dialog.on_cancel_requested(move || {
        if let Some(dialog) = dialog_weak.upgrade() {
            let _ = dialog.hide();
        }
        *auth_window_for_cancel.borrow_mut() = None;
        if let Some(host) = host_for_cancel.upgrade() {
            host.set_connection_test_status(SharedString::from(
                "StoryLock open blocked: authorization cancelled.",
            ));
        }
    });

    let dialog_weak = dialog.as_weak();
    let host_for_close = host_weak.clone();
    let auth_window_for_close = Rc::clone(&auth_window);
    dialog.window().on_close_requested(move || {
        if let Some(dialog) = dialog_weak.upgrade() {
            let _ = dialog.hide();
        }
        *auth_window_for_close.borrow_mut() = None;
        if let Some(host) = host_for_close.upgrade() {
            host.set_connection_test_status(SharedString::from(
                "StoryLock open blocked: authorization cancelled.",
            ));
        }
        slint::CloseRequestResponse::HideWindow
    });

    dialog.show()?;
    *auth_window.borrow_mut() = Some(dialog);
    Ok(())
}

#[derive(Clone, Debug)]
pub(super) struct StoryLockChallengeCell {
    pub(super) cell_id: String,
    pub(super) prompt_text: String,
    pub(super) answer_options: Vec<String>,
    pub(super) expected_answers: Vec<String>,
    pub(super) expected_count: usize,
}

pub(super) fn create_storylock_open_challenge(
    package_dir: &Path,
    required_cells: usize,
) -> Result<Vec<StoryLockChallengeCell>> {
    let draft = read_effective_author_draft(package_dir);
    let nodes = draft
        .get("nodes")
        .and_then(Value::as_array)
        .ok_or_else(|| anyhow::anyhow!("StoryLock draft has no question nodes"))?;
    if nodes.len() < required_cells {
        return Err(anyhow::anyhow!(
            "StoryLock draft has fewer than {required_cells} questions"
        ));
    }
    let cells = nodes
        .iter()
        .take(required_cells)
        .enumerate()
        .map(|(index, node)| {
            let options = node
                .get("answerOptionsLocalOnly")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default();
            let mut answer_options = options
                .iter()
                .take(9)
                .map(|option| {
                    option
                        .get("text")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string()
                })
                .collect::<Vec<_>>();
            while answer_options.len() < 9 {
                answer_options.push(String::new());
            }
            let expected_answers = options
                .iter()
                .filter(|option| {
                    option
                        .get("isCorrect")
                        .and_then(Value::as_bool)
                        .unwrap_or(false)
                })
                .filter_map(|option| option.get("text").and_then(Value::as_str))
                .map(normalize_challenge_answer)
                .filter(|answer| !answer.is_empty())
                .collect::<Vec<_>>();
            let expected_count = expected_answers.len();
            StoryLockChallengeCell {
                cell_id: node
                    .get("nodeId")
                    .and_then(Value::as_str)
                    .map(ToOwned::to_owned)
                    .unwrap_or_else(|| format!("node-{:02}", index + 1)),
                prompt_text: node
                    .get("question")
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string(),
                answer_options,
                expected_answers,
                expected_count,
            }
        })
        .collect::<Vec<_>>();
    if cells.iter().any(|cell| {
        cell.prompt_text.trim().is_empty()
            || cell.answer_options.iter().all(|answer| answer.trim().is_empty())
            || cell.expected_answers.is_empty()
    }) {
        return Err(anyhow::anyhow!(
            "StoryLock challenge contains incomplete question or answer data"
        ));
    }
    Ok(cells)
}

pub(super) fn authorize_storylock_open(
    cells: &[StoryLockChallengeCell],
    answers: &[Vec<String>],
) -> Result<()> {
    if answers.len() != cells.len() {
        return Err(anyhow::anyhow!(
            "challenge answer count mismatch: expected {}, got {}",
            cells.len(),
            answers.len()
        ));
    }
    for (index, (cell, answer)) in cells.iter().zip(answers.iter()).enumerate() {
        let selected = answer
            .iter()
            .map(|answer| normalize_challenge_answer(answer))
            .filter(|answer| !answer.is_empty())
            .collect::<HashSet<_>>();
        let expected = cell
            .expected_answers
            .iter()
            .cloned()
            .collect::<HashSet<_>>();
        if selected != expected {
            return Err(anyhow::anyhow!(
                "第 {} 题不匹配，已选 {}/应选 {}",
                index + 1,
                selected.len(),
                expected.len()
            ));
        }
    }
    Ok(())
}

pub(super) fn toggle_storylock_challenge_selection(
    cells: &[StoryLockChallengeCell],
    selections: &mut [Vec<String>],
    current_index: usize,
    answer_index: usize,
) {
    let selected = cells
        .get(current_index)
        .and_then(|cell| cell.answer_options.get(answer_index))
        .cloned()
        .unwrap_or_default();
    if selected.trim().is_empty() {
        return;
    }
    if let Some(slot) = selections.get_mut(current_index) {
        let normalized = normalize_challenge_answer(&selected);
        if let Some(existing_index) = slot
            .iter()
            .position(|answer| normalize_challenge_answer(answer) == normalized)
        {
            slot.remove(existing_index);
        } else {
            slot.push(selected);
        }
    }
}

pub(super) fn normalize_challenge_answer(answer: &str) -> String {
    answer.trim().to_lowercase()
}

fn show_storylock_authorization_result(title: &str, message: &str, success: bool) {
    let title = wide_null(title);
    let message = wide_null(message);
    let icon = if success {
        MB_ICONINFORMATION
    } else {
        MB_ICONERROR
    };
    unsafe {
        MessageBoxW(
            std::ptr::null_mut(),
            message.as_ptr(),
            title.as_ptr(),
            MB_OK | icon,
        );
    }
}

fn wide_null(value: &str) -> Vec<u16> {
    value.encode_utf16().chain(std::iter::once(0)).collect()
}

fn set_storylock_challenge_question(
    dialog: &StoryLockAuthorizationDialog,
    cells: &[StoryLockChallengeCell],
    selections: &[Vec<String>],
    index: usize,
) {
    let cell = cells.get(index);
    let option = |option_index: usize| -> SharedString {
        SharedString::from(
            cell
                .and_then(|cell| cell.answer_options.get(option_index))
                .map(String::as_str)
                .unwrap_or(""),
        )
    };
    let prompt = cell
        .map(|cell| cell.prompt_text.as_str())
        .unwrap_or("");
    let cell_id = cell
        .map(|cell| cell.cell_id.as_str())
        .unwrap_or("");
    dialog.set_current_index(index as i32);
    let selected_count = selections.get(index).map(Vec::len).unwrap_or_default();
    let expected_count = cell.map(|cell| cell.expected_count).unwrap_or_default();
    dialog.set_current_position(SharedString::from(format!(
        "{}/{} - 已选 {}/应选 {}",
        index + 1,
        cells.len(),
        selected_count,
        expected_count
    )));
    let missing = cells
        .iter()
        .enumerate()
        .filter(|(cell_index, _)| selections.get(*cell_index).map(Vec::is_empty).unwrap_or(true))
        .map(|(cell_index, _)| (cell_index + 1).to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let prompt_text = if missing.is_empty() {
        prompt.to_string()
    } else {
        format!("{prompt} | 未完成题号: {missing}")
    };
    dialog.set_current_prompt(SharedString::from(if cell_id.is_empty() {
        prompt_text
    } else {
        prompt_text
    }));
    dialog.set_selected_answer(SharedString::from(
        selections
            .get(index)
            .map(|answers| answers.join("; "))
            .unwrap_or_default(),
    ));
    dialog.set_option_1(option(0));
    dialog.set_option_2(option(1));
    dialog.set_option_3(option(2));
    dialog.set_option_4(option(3));
    dialog.set_option_5(option(4));
    dialog.set_option_6(option(5));
    dialog.set_option_7(option(6));
    dialog.set_option_8(option(7));
    dialog.set_option_9(option(8));
    let state = |option_index: usize| -> SharedString {
        let option_value = cell
            .and_then(|cell| cell.answer_options.get(option_index))
            .map(String::as_str)
            .unwrap_or("");
        let option_normalized = normalize_challenge_answer(option_value);
        let selected = selections
            .get(index)
            .is_some_and(|answers| {
                answers
                    .iter()
                    .any(|answer| normalize_challenge_answer(answer) == option_normalized)
            });
        SharedString::from(if selected && !option_normalized.is_empty() {
            "correct"
        } else {
            "wrong"
        })
    };
    dialog.set_option_1_state(state(0));
    dialog.set_option_2_state(state(1));
    dialog.set_option_3_state(state(2));
    dialog.set_option_4_state(state(3));
    dialog.set_option_5_state(state(4));
    dialog.set_option_6_state(state(5));
    dialog.set_option_7_state(state(6));
    dialog.set_option_8_state(state(7));
    dialog.set_option_9_state(state(8));
}

fn test_managed_object_nine_grid(host_port: u16, tier: String) -> String {
    let client = match Client::builder().timeout(Duration::from_secs(8)).build() {
        Ok(client) => client,
        Err(error) => return format!("Nine-grid test failed: client setup failed: {error}"),
    };
    let status_url = format!("http://127.0.0.1:{host_port}/ui/status");
    let status = match client.get(&status_url).send() {
        Ok(response) => match response.json::<Value>() {
            Ok(value) => value,
            Err(error) => {
                return format!("Nine-grid test failed: could not parse ui status: {error}");
            }
        },
        Err(error) => return format!("Nine-grid test failed: could not read ui status: {error}"),
    };
    let management = status
        .get("result")
        .and_then(Value::as_object)
        .and_then(|result| result.get("managementStats"))
        .cloned()
        .unwrap_or(Value::Null);
    let object = management
        .get("objects")
        .and_then(Value::as_array)
        .and_then(|objects| objects.first())
        .cloned();
    let Some(object) = object else {
        return "Nine-grid test failed: no managed objects available yet".to_string();
    };
    let object_ref = object
        .get("objectRef")
        .and_then(Value::as_str)
        .unwrap_or("unknown-object");
    let (authorization_channel, requested_action, capability, label) = match tier.as_str() {
        "confidential" => (
            "batch_read",
            "batch_read",
            "requestPasswordFill",
            "Confidential object",
        ),
        "top-secret" => (
            "story_edit",
            "story_edit",
            "requestPasswordFill",
            "Top secret object",
        ),
        _ => (
            "single_read",
            "password_fill",
            "requestPasswordFill",
            "Standard object",
        ),
    };
    let verification_request = json!({
        "requestId": format!("req-nine-grid-{}", Uuid::new_v4()),
        "capability": capability,
        "credentialRef": object_ref,
        "authorizationChannel": authorization_channel,
        "requestedAction": requested_action,
        "requester": "host-ui-nine-grid"
    });
    let verify_url = format!("http://127.0.0.1:{host_port}/verify");
    let verification = match client.post(&verify_url).json(&verification_request).send() {
        Ok(response) => match response.json::<Value>() {
            Ok(value) => value,
            Err(error) => {
                return format!(
                    "Nine-grid test failed: could not parse verification response: {error}"
                );
            }
        },
        Err(error) => return format!("Nine-grid test failed: verify request failed: {error}"),
    };
    let result = verification.get("result").cloned().unwrap_or(Value::Null);
    let verification_id = result
        .get("verificationId")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let grid = result.get("grid").cloned().unwrap_or(Value::Null);
    let required_cells = grid
        .get("requiredCells")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    let grid_size = grid.get("gridSize").and_then(Value::as_u64).unwrap_or(0);
    format!(
        "Nine-grid ready: {label}, object={object_ref}, verificationId={verification_id}, {required_cells}/{grid_size} cells"
    )
}
