use super::*;

pub fn run(config: WindowsHostConfig) -> Result<()> {
    let app = HostDashboard::new()?;
    app.set_product(SharedString::from(config.product.clone()));
    app.set_version(SharedString::from(config.version.clone()));
    app.set_mode(SharedString::from(if config.remote_enabled {
        "Remote relay enabled"
    } else {
        "Local only"
    }));
    app.set_identity_id(SharedString::from(config.identity_id.clone()));
    app.set_device_id(SharedString::from(config.device_id.clone()));
    app.set_local_api(SharedString::from(config.health_url.clone()));
    app.set_capabilities(SharedString::from(if config.remote_enabled {
        "health, verify, authorize, revoke, execute, relay_poll"
    } else {
        "health, verify, authorize, revoke, execute"
    }));
    app.set_call_chain(SharedString::from(
        "verify -> authorize -> execute -> revoke",
    ));
    app.set_management_stats(SharedString::from(format!(
        "Live redacted statistics are available at http://127.0.0.1:{}/ui and /ui/status.\n\nYian Host may show authorization modes, required grid cells, managed-object call counts, agent/requester counts, remote-interface access counts, and error-call totals.\n\nStory template candidates can be generated by Host and queued at /story-template/generate; StoryLock must explicitly pull them from /story-template/candidates. Host never invokes StoryLock.\n\nLLM keys are direct-access generator config. Host may show configured/missing, but must not display key values.\n\nIt must not display StoryLock drafts, vault files, package paths, question answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.",
        config.host_port
    )));
    app.set_diagnostics(SharedString::from(
        "Yian Host is storage-blind. It does not read or display StoryLock drafts, vault files, manifests, catalogs, templates, package paths, question answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.",
    ));
    let saved_settings = Rc::new(RefCell::new(load_storylock_ui_settings()));
    let initial_language = saved_settings
        .borrow()
        .language
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| String::from("zh"));
    app.set_language(SharedString::from(initial_language.clone()));

    let local_health_url = config.health_url.clone();
    app.on_test_local_host(move || {
        SharedString::from(test_http_endpoint("Local Host", &local_health_url))
    });

    let remote_gateway_url = config.gateway_base_url.clone();
    app.on_test_remote_connection(move || {
        SharedString::from(test_http_endpoint("Remote Gateway", &remote_gateway_url))
    });

    let host_port_for_nine_grid = config.host_port;
    app.on_test_managed_object_nine_grid(move |tier| {
        SharedString::from(test_managed_object_nine_grid(
            host_port_for_nine_grid,
            tier.to_string(),
        ))
    });

    let host_language = Rc::new(RefCell::new(initial_language));
    let core_package_dir = initial_storylock_core_package_dir(&saved_settings.borrow());
    let _ = ensure_storylock_core_package(&core_package_dir);
    app.set_management_stats(SharedString::from(format!(
        "Live redacted statistics are available at http://127.0.0.1:{}/ui and /ui/status.\n\n{}\n\nYian Host reads learning-policy.json for retention-learning scheduling, but does not read StoryLock drafts, vault files, question text, answers, passwords, private keys, signing key bytes, shared secrets, or raw story text.",
        config.host_port,
        host_learning_plan_status(&core_package_dir)
    )));

    let core_window: Rc<RefCell<Option<StoryLockCoreApp>>> = Rc::new(RefCell::new(None));
    let settings_window: Rc<RefCell<Option<SettingsDialog>>> = Rc::new(RefCell::new(None));
    let settings_window_for_open = Rc::clone(&settings_window);
    let host_for_settings = app.as_weak();
    let host_language_for_settings = Rc::clone(&host_language);
    let core_window_for_settings = Rc::clone(&core_window);
    let host_for_settings_lock = app.as_weak();
    let shared_status = Rc::new(RefCell::new(String::from("")));
    let shared_status_for_settings = Rc::clone(&shared_status);
    let saved_settings_for_settings = Rc::clone(&saved_settings);

    app.on_open_settings(move || {
        let existing_show_result = {
            settings_window_for_open
                .borrow()
                .as_ref()
                .map(|existing| existing.show())
        };
        if let Some(show_result) = existing_show_result {
            if let Err(error) = show_result {
                eprintln!("failed to show settings window: {error}");
                *settings_window_for_open.borrow_mut() = None;
                if let Some(host) = host_for_settings.upgrade() {
                    host.set_settings_open(false);
                    host.set_connection_test_status(SharedString::from(format!(
                        "Settings reopen failed: {error}"
                    )));
                }
            } else if let Some(host) = host_for_settings.upgrade() {
                host.set_settings_open(true);
                host.set_connection_test_status(SharedString::from("Settings opened"));
            }
            return;
        }

        match SettingsDialog::new() {
            Ok(settings) => {
                settings.set_language(SharedString::from(
                    host_language_for_settings.borrow().clone(),
                ));
                settings.set_core_launch_status(SharedString::from(
                    shared_status_for_settings.borrow().clone(),
                ));

                if let Some(host) = host_for_settings.upgrade() {
                    host.set_connection_test_status(SharedString::from("Settings opened"));
                    host.set_settings_open(true);
                }

                let settings_weak = settings.as_weak();
                let settings_weak_for_close = settings_weak.clone();
                let host_for_language = host_for_settings.clone();
                let host_language_for_language = Rc::clone(&host_language_for_settings);
                let core_window_for_language = Rc::clone(&core_window_for_settings);
                let saved_settings_for_language = Rc::clone(&saved_settings_for_settings);

                settings.on_language_changed(move |language| {
                    let language_string = language.to_string();
                    *host_language_for_language.borrow_mut() = language_string.clone();
                    let next_settings = merge_host_language_setting(
                        &saved_settings_for_language.borrow(),
                        &language_string,
                    );
                    if let Err(error) = save_storylock_ui_settings(&next_settings) {
                        eprintln!("failed to save StoryLock UI settings: {error}");
                    }
                    *saved_settings_for_language.borrow_mut() = next_settings;

                    if let Some(settings) = settings_weak.upgrade() {
                        settings.set_language(SharedString::from(language_string.clone()));
                    }
                    if let Some(host) = host_for_language.upgrade() {
                        host.set_language(SharedString::from(language_string.clone()));
                        host.set_connection_test_status(SharedString::from(
                            "Language changed, settings stay open",
                        ));
                    }
                    if let Some(core) = core_window_for_language.borrow().as_ref() {
                        core.set_language(SharedString::from(language_string));
                    }
                });

                let host_for_settings_lock_close = host_for_settings_lock.clone();
                let host_language_for_close = Rc::clone(&host_language_for_settings);
                let settings_window_for_close = Rc::clone(&settings_window_for_open);
                let close_settings = Rc::new(move |settings: &SettingsDialog| {
                    let _ = settings.hide();
                    *settings_window_for_close.borrow_mut() = None;
                    if let Some(host) = host_for_settings_lock_close.upgrade() {
                        host.set_settings_open(false);
                        let text = if host_language_for_close.borrow().as_str() == "zh" {
                            "设置已关闭"
                        } else {
                            "Settings closed"
                        };
                        host.set_connection_test_status(SharedString::from(text));
                    }
                });

                let close_settings_for_button = Rc::clone(&close_settings);
                settings.on_close_requested(move || {
                    if let Some(settings) = settings_weak_for_close.upgrade() {
                        close_settings_for_button(&settings);
                    }
                });

                let settings_weak_for_window_close = settings.as_weak();
                let close_settings_for_window = Rc::clone(&close_settings);
                settings.window().on_close_requested(move || {
                    if let Some(settings) = settings_weak_for_window_close.upgrade() {
                        close_settings_for_window(&settings);
                    }
                    slint::CloseRequestResponse::HideWindow
                });

                if let Err(error) = settings.show() {
                    eprintln!("failed to show settings window: {error}");
                    return;
                }
                *settings_window_for_open.borrow_mut() = Some(settings);
            }
            Err(error) => eprintln!("failed to create settings window: {error}"),
        }
    });

    let core_window_for_callback = Rc::clone(&core_window);
    let host_for_storylock_close = app.as_weak();
    let settings_window_for_storylock_close = Rc::clone(&settings_window);
    let shared_status_for_storylock_close = Rc::clone(&shared_status);
    let host_language_for_storylock = Rc::clone(&host_language);
    let saved_settings_for_storylock = Rc::clone(&saved_settings);

    app.on_open_storylock_core(move || {
        let current_settings = saved_settings_for_storylock.borrow().clone();
        let active_package_dir = initial_storylock_core_package_dir(&current_settings);
        if let Err(error) = ensure_storylock_core_package(&active_package_dir) {
            eprintln!("failed to initialize StoryLock Core package: {error}");
        }

        if let Some(core) = core_window_for_callback.borrow().as_ref() {
            initialize_storylock_core_window(core, &active_package_dir);
            core.set_language(SharedString::from(
                host_language_for_storylock.borrow().clone(),
            ));
            apply_storylock_ui_settings(core, &current_settings);
            set_storylock_start_page_to_questions(core);
            core.set_config_status(SharedString::from(
                "StoryLock Core is already open. Existing local window was focused.",
            ));
            if let Err(error) = core.show() {
                eprintln!("failed to show existing StoryLock Core window: {error}");
            } else {
                return;
            }
        }

        *core_window_for_callback.borrow_mut() = None;
        match StoryLockCoreApp::new() {
            Ok(core) => {
                core.set_language(SharedString::from(
                    host_language_for_storylock.borrow().clone(),
                ));
                initialize_storylock_core_window(&core, &active_package_dir);
                apply_storylock_ui_settings(&core, &current_settings);
                set_storylock_start_page_to_questions(&core);
                let host_for_closed = host_for_storylock_close.clone();
                let settings_window_for_closed = Rc::clone(&settings_window_for_storylock_close);
                let shared_status_for_closed = Rc::clone(&shared_status_for_storylock_close);
                let notify_storylock_closed: Rc<dyn Fn()> = Rc::new(move || {
                    let status = "StoryLock closed".to_string();
                    *shared_status_for_closed.borrow_mut() = status.clone();
                    if let Some(host) = host_for_closed.upgrade() {
                        host.set_connection_test_status(SharedString::from(status.clone()));
                    }
                    if let Some(settings) = settings_window_for_closed.borrow().as_ref() {
                        settings.set_core_launch_status(SharedString::from(status));
                    }
                });
                wire_storylock_core_callbacks(
                    &core,
                    active_package_dir,
                    Rc::clone(&core_window_for_callback),
                    notify_storylock_closed,
                    config.host_port,
                );
                if let Err(error) = core.show() {
                    eprintln!("failed to show StoryLock Core window: {error}");
                    return;
                }
                *core_window_for_callback.borrow_mut() = Some(core);
            }
            Err(error) => {
                eprintln!("failed to create StoryLock Core window: {error}");
            }
        }
    });

    let weak = app.as_weak();
    let host_language_for_close = Rc::clone(&host_language);
    let saved_settings_for_close = Rc::clone(&saved_settings);
    app.on_close_requested(move || {
        let next_settings = merge_host_language_setting(
            &saved_settings_for_close.borrow(),
            &host_language_for_close.borrow(),
        );
        if let Err(error) = save_storylock_ui_settings(&next_settings) {
            eprintln!("failed to save StoryLock UI settings: {error}");
        }
        *saved_settings_for_close.borrow_mut() = next_settings;
        if let Some(app) = weak.upgrade() {
            let _ = app.hide();
        }
    });

    app.run()?;
    let final_settings =
        merge_host_language_setting(&saved_settings.borrow(), &host_language.borrow());
    if let Err(error) = save_storylock_ui_settings(&final_settings) {
        eprintln!("failed to save StoryLock UI settings: {error}");
    }
    Ok(())
}

fn test_http_endpoint(label: &str, url: &str) -> String {
    let client = match Client::builder().timeout(Duration::from_secs(5)).build() {
        Ok(client) => client,
        Err(error) => return format!("{label}: client setup failed: {error}"),
    };
    match client.get(url).send() {
        Ok(response) if response.status().is_success() => {
            format!("{label}: OK ({})", response.status())
        }
        Ok(response) => format!("{label}: HTTP {}", response.status()),
        Err(error) => format!("{label}: failed: {error}"),
    }
}

fn test_managed_object_nine_grid(host_port: u16, tier: String) -> String {
    let client = match Client::builder().timeout(Duration::from_secs(8)).build() {
        Ok(client) => client,
        Err(error) => return format!("Nine-grid test failed: client setup failed: {error}"),
    };
    let status_url = format!("http://127.0.0.1:{host_port}/ui/status");
    let status = match client.get(&status_url).send() {
        Ok(response) => match response.json::<Value>() {
            Ok(value) => value,
            Err(error) => {
                return format!("Nine-grid test failed: could not parse ui status: {error}");
            }
        },
        Err(error) => return format!("Nine-grid test failed: could not read ui status: {error}"),
    };
    let management = status
        .get("result")
        .and_then(Value::as_object)
        .and_then(|result| result.get("managementStats"))
        .cloned()
        .unwrap_or(Value::Null);
    let object = management
        .get("objects")
        .and_then(Value::as_array)
        .and_then(|objects| objects.first())
        .cloned();
    let Some(object) = object else {
        return "Nine-grid test failed: no managed objects available yet".to_string();
    };
    let object_ref = object
        .get("objectRef")
        .and_then(Value::as_str)
        .unwrap_or("unknown-object");
    let (authorization_channel, requested_action, capability, label) = match tier.as_str() {
        "confidential" => (
            "batch_read",
            "batch_read",
            "requestPasswordFill",
            "Confidential object",
        ),
        "top-secret" => (
            "story_edit",
            "story_edit",
            "requestPasswordFill",
            "Top secret object",
        ),
        _ => (
            "single_read",
            "password_fill",
            "requestPasswordFill",
            "Standard object",
        ),
    };
    let verification_request = json!({
        "requestId": format!("req-nine-grid-{}", Uuid::new_v4()),
        "capability": capability,
        "credentialRef": object_ref,
        "authorizationChannel": authorization_channel,
        "requestedAction": requested_action,
        "requester": "host-ui-nine-grid"
    });
    let verify_url = format!("http://127.0.0.1:{host_port}/verify");
    let verification = match client.post(&verify_url).json(&verification_request).send() {
        Ok(response) => match response.json::<Value>() {
            Ok(value) => value,
            Err(error) => {
                return format!(
                    "Nine-grid test failed: could not parse verification response: {error}"
                );
            }
        },
        Err(error) => return format!("Nine-grid test failed: verify request failed: {error}"),
    };
    let result = verification.get("result").cloned().unwrap_or(Value::Null);
    let verification_id = result
        .get("verificationId")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let grid = result.get("grid").cloned().unwrap_or(Value::Null);
    let required_cells = grid
        .get("requiredCells")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    let grid_size = grid.get("gridSize").and_then(Value::as_u64).unwrap_or(0);
    format!(
        "Nine-grid ready: {label}, object={object_ref}, verificationId={verification_id}, {required_cells}/{grid_size} cells"
    )
}
